ersion: '3.9'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 2Years*end2022
      POSTGRES_USER: postgres
      POSTGRES_DB: rentafacil
    ports:
      - 5432:5432