name: deploy

on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: namemc
          password: dckr_pat_r978Y-nYEwweuP-Bf9wI0iSDQZA
      -
        name: Set up Docker Build
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with: 
          context: ./back
          file: ./back/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce:latest
