name: deploy

on: 
  push:
    branches:
    - "main"
jobs: 
  build:
    runs-on: ubuntu-lates
    steps:
    - 
      name: Checkout
      uses: actions/@checkout@v4
    -
      name: Login to Docker hub
      uses: docker/login-action@v3
      with:
        username: ${{secrect.DOCKERHUB_USERNAME}}
        password: ${{secret.DOCKERHUB_TOKEN}}
    -
      name: Set up Docker Build
      uses: docker/setup-buildx-action@v3
    -  
      name: Build and push
      uses: docker/build-push/action@v5
      with: 
        contex: .
        file: ./Dockerfile
        push: true
        tags: ~${{secret.DOCKERHUB_USERNAME}}/rentafalcil:latests
