name: deploy

on:
  push:
    branches: 
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - 
      name: checkout
      uses: actions/checkout@v4
    -
      name: login to docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        passowrd: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: set up docker build
      uses: docker/setuo-buildx-action@v3
    -
      name: build and push
      uses: docker/build-push-action@v5
      with: 
        contex: ./back
        file: ./back/Dockerfile
        build: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/rentafacil:latest
